INSERT INTO ROLES(ID,NAME, STATUS,CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES (1,'ROLE_ADMIN',1,current_timestamp,1,current_timestamp,1);
INSERT INTO ROLES(ID,NAME, STATUS,CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES (2,'ROLE_CUSTOMER',1,current_timestamp,1,current_timestamp,1);

INSERT INTO USERS(ID,EMAIL,NAME,PASSWORD,STATUS,SURNAME,USERNAME,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES(1,'admin@admin.com','admin-name','$2a$10$Mxk9PzP.OdKeFw9ev6BOeekl88XoaIJn1pUe.CyO76TzPUe5fmjvO',1,'admin-surname','admin',current_timestamp,0,current_timestamp,0);
INSERT INTO USERS(ID,EMAIL,NAME,PASSWORD,STATUS,SURNAME,USERNAME,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES(2,'user@user.com','user-name','$2a$10$YqqRwpauQyLDGR4LHoouzeOwGdv7PD7j1GRAa2QFoaY/nG2KbxOVe',1,'user-surname','user',current_timestamp,1,current_timestamp,1);

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2,2);

INSERT INTO BOOKS (ID,AUTHOR,NAME,PRICE,STATUS,STOCK,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES(1,'Lev Tolstoy','Anna Karenina 1',10.10,1,10,current_timestamp,1,current_timestamp,1);
INSERT INTO BOOKS (ID,AUTHOR,NAME,PRICE,STATUS,STOCK,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES(2,'Lev Tolstoy','Anna Karenina 2',20.10,1,20,current_timestamp,1,current_timestamp,1);
INSERT INTO BOOKS (ID,AUTHOR,NAME,PRICE,STATUS,STOCK,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES(3,'Lev Tolstoy','Anna Karenina 3',30.10,1,30,current_timestamp,1,current_timestamp,1);

INSERT INTO ORDERS (ID,BOOK_ID,CUSTOMER_ID,ORDER_STATUS,QUANTITY,TOTAL_PRICE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES(1,1,2,1,3,30.30,current_timestamp ,2,current_timestamp,2)